
default: &default
  adapter: postgresql
  encoding: unicode
  database: testdb_production
  username: Admin
  password: pass123
  host: localhost
  port: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
